# Generated by Django 3.2.4 on 2021-08-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210722_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cat',
            new_name='bird',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='badger',
            new_name='rodent',
        ),
    ]
