# Generated by Django 3.2.4 on 2021-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210804_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bird',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='image',
            name='fox',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='image',
            name='rodent',
            field=models.FloatField(default=-1.0),
        ),
    ]
