version: "3.9"

services:

  # Localstack
  localstack:
    container_name: local_stack
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID='test'
      - AWS_SECRET_KEY='test
      - DISABLE_CORS_CHECKS=1
    volumes:
      - "${PWD}/infrastructure/s3:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # Postgres
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/infrastructure/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6389:6389
    command: redis-server --port 6389 --requirepass z5AS92W5Z9ID

  # Django
  api:
    build:
      context: ${PWD}/api/
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    environment:
      - ENVIRONMENT=LOCAL
    volumes:
      - ${PWD}/api/src:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  # Base Celery Worker
  celery_worker:
    build:
      context: ${PWD}/api/
    command: >
      sh -c "celery --app api.celery:CELERY_APP worker --loglevel=DEBUG --concurrency=1 --max-tasks-per-child=1"
    working_dir: /code
    environment:
      - ENVIRONMENT=LOCAL
    volumes:
      - ${PWD}/api/src:/code
    depends_on:
      - redis
      - db